add small thread sleep between publishes - for #224
sunng87/cargo-release pull request #247
Opened 2020-12-26 15:52 UTC by clux

Hey all. Thank you for cargo-release. It's very helpful!
This particular issue (#224) keeps biting me, and while this PR has only a dumb/ugly solution, I do think it should fix the problem. If the chosen time is bad, we could parametrise the second value into argv.

(it's probably possible to write a more advanced solution with a curl to crates.io to check that the previous upload has completed, but I'm not even sure that's perfect if all that's happening under the hood is that the write operation (the publish) propagates to all of crates' replicas.)

2020-12-26 17:25 UTC, epage requested changes
We need to reach out to the crates.io team to figure out what is happening but that shouldn't block making things work for people.

2020-12-26 17:25 UTC, epage commented on src/main.rs
>                  cargo::wait_for_publish(crate_name, &base.version_string, timeout, dry_run)?;
> (it's probably possible to write a more advanced solution with a curl to crates.io to check that the previous upload has completed, but I'm not even sure that's perfect if all that's happening under the hood is that the write operation (the publish) propagates to all of crates' replicas.)

In theory, that is what `wait_for_publish` is doing but for some  reason, it isn't.  Looking at people's logs in #224, we are waiting, for example
```
[2020-09-10T07:57:34Z INFO ] Waiting for publish to complete...
[2020-09-10T07:57:40Z INFO ] Running cargo publish on kube
```
Here we waited for 6s.  Yet somehow, it wasn't good enough.  Apparently, the part of the index we are checking gets updated but not everything needed to publishing.  We are then racing for that to be updated.

2020-12-26 17:25 UTC, epage commented on src/main.rs
> +                std::time::Duration::from_secs(5);
Maybe update the comment, based on my above analysis

```
// HACK: Even once the index is updated, there seems to be another step before the publish is fully ready.  We don't have a way yet to check for that, so waiting for now in hopes everything is ready
```
Also, should this be in `wait_for_publish`?  On one hand, it keeps all related logic together.  On the other hand, its helpful to have hacks stand out.

2020-12-26 18:05 UTC, clux commented on src/main.rs
>                  cargo::wait_for_publish(crate_name, &base.version_string, timeout, dry_run)?;
Yeah, I am not sure. AFAIKT from the documentation in https://docs.rs/crates-index/0.16.2/crates_index/struct.Index.html you are doing the right thing in `wait_for_publish`.

2020-12-26 18:06 UTC, clux commented on src/main.rs
> +                std::time::Duration::from_secs(5);
Have updated the comment. I think the `wait_for_publish` is doing the right thing, so maybe it just takes some times for writes to crates.io to propagate to all its read-replicas. At any rate, it's only a problem when publishing more than one crate, so probably good to keep the hack here.

2020-12-26 18:55 UTC, epage commented on src/main.rs
> +                std::time::Duration::from_secs(5);
The insiduous thing about race conditions is you can never know if your change actually helped because you might have just not hit the race when testing your fix.  Or the problem might go away and you don't need the hack anymore

:(

2020-12-26 18:55 UTC, epage approved these changes

2020-12-26 18:56 UTC, merged

2021-02-21 20:20 UTC, yrashk commented
It looks like I am hitting the issue of not waiting enough before one of the newly published crates is available before proceeding to the next one. Makes it much harder to resume the process.

2021-02-21 20:24 UTC, yrashk commented
Maybe it would make sense to allow continuing if trying to re-upload a crate with the same version?